### ISSUE TITLE
License server on the Windows and Zabbix on Linux

### ISSUE THREAD

**Issue by kokotko1337** [speculatrix/zabbix-flexlm#1]
Hi , 
For this template must be license server on the Zabbix Host ? 

Got enviroment where License Server is windows host and im able to read data on Zabbix server from Windows License host. Is there any way how can I use this template ?

**Comment by speculatrix** [comment]
Hi,
the zabbix agent must be running on the same host as the licence server.

The agent runs a script because of the .conf file you put on the agent. You would have to rewrite the script to run on a Windows host. I guess you could use powershell or something, but I can't help you with that. Feel free to fork this repo, and then submit a pull request with a new .conf and script for windows.

Paul

**Comment by kokotko1337** [comment]
Thanks for reply ... Just found PL ext script which is working from Linux Zabbix to Windows license server like a dream ... If someone innterested: https://www.zabbix.com/forum/zabbix-cookbook/38199-monitoring-flexlm-license-usage

**Comment by speculatrix** [comment]
thanks for that, I posted a link to here.
